### PR TITLE
Fix some OS X stuff

### PR DESCRIPTION
**Pull request by LinusU**
The first commit fixes the detection of SDL2_ttf, at least on my Mac. I don't know atm why I can't specify both at the same time, but when I do that, only the first show up in the linker flags.

The second commit fixes the header inclusion in the network code in a better way than before. It does two things:

1. Changing `<math.h>` to `<cmath>` since it's in c++ code.
2. Adding `<errno.h>` to the C part of the header, `errno` is used only 9 lines below so I really think this should be needed. (also, it doesn't compile for me without it with clang 7.0)

### CODE REVIEW

**Comment by janisozaur** [comment]
Can we investigate what's happening with your cmake before this goes in? This change (to `CMakeLists.txt`) shouldn't be required, so I say the problem is on your end.

Can you add `--trace` to your cmake invocation and check it looks as expected? I've just pushed similar change to my osx branch, so these "expected results" should be available on travis soon enough: https://travis-ci.org/janisozaur/OpenRCT2/builds/87835572

**Comment by janisozaur** [comment]
And one more with `--debug-output` too: https://travis-ci.org/janisozaur/OpenRCT2/builds/87835943

**Comment by LinusU** [comment]
For some reason I still need the SDL2_ttf fix :sob:

**Comment by LinusU** [comment]
Rebased on your latest `osx` branch though. What do you think of the second commit, 9fc5f5e?

**Comment by janisozaur** [comment]
I still insist that the `SDL2_ttf` detection problem is at your side of things. I've built numerous on OS X to this date and not once have encountered the problem you describe. See latest travis build: https://travis-ci.org/janisozaur/OpenRCT2/builds/93308107

Can you show what pkg-config returns for:
```
pkg-config --cflags --libs sdl2 SDL2_ttf
```
on your system?

Regarding inclusion of `errno.h` I'm somewhat torn. On one hand it works as is now, but on the other it's good practice to provide a full set of includes in a way that header automatically pulls all of its required dependencies. All in all I'm in favor of the change.

**Comment by LinusU** [comment]
Yeah I agree on that the error is on my side, just need to figure out why :)

I'm at work now but I'll check when I get home :+1:

**Comment by janisozaur** [comment]
as this is mostly included in upstream now, i'm going to close it.

**Comment by LinusU** [comment]
:+1: 

Also, this is the output, looks all right to me. I just can't figure this out :confounded: 

```text
➜  ~  pkg-config --cflags --libs sdl2 SDL2_ttf
-D_THREAD_SAFE -I/usr/local/include/SDL2 -L/usr/local/lib -lSDL2_ttf -lSDL2
```

**Pull request closed without merging**
